### PR TITLE
KAFKA-17939: Make Bytes part of the public API (KIP-1247)

### PR DESCRIPTION
**Pull request by siddharthaDevineni**
### Summary
This PR implements
[KIP-1247](https://cwiki.apache.org/confluence/display/KAFKA/KIP-1247%3A+Make+Bytes+utils+class+part+of+the+public+API)
to officially make the `Bytes` class part of Kafka's public API.

### Changes
- Add `Bytes` to Javadoc generation in `build.gradle`
- Deprecate helper methods that are not part of the intended public API:
  - `increment()`
  - `BYTES_LEXICO_COMPARATOR`
  - `ByteArrayComparator`
- Create `org.apache.kafka.common.utils.internals.BytesUtils` with
duplicates of deprecated helpers
- Update all internal Kafka code to use `BytesUtils` instead of
deprecated methods
- Enhance Javadoc documentation for core `Bytes` methods

### Compatibility
Deprecated methods will remain functional until version 5.0 to maintain
backward compatibility for any external users who may be relying on
them.

### Testing
- All existing `BytesTest` tests pass
- Verified Javadoc generation includes `Bytes` class
- Verified all internal references compile correctly

Reviewers: Sean Quah <squah@confluent.io>, Kuan-Po Tseng
 <brandboat@gmail.com>, Chia-Ping Tsai <chia7712@gmail.com>

### CODE REVIEW

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java [hunk 1]
```diff
@@ -146,7 +163,10 @@ private static String toString(final byte[] b, int off, int len) {
      *
      * @param input - The byte array to increment
      * @return A new copy of the incremented byte array.
+     * @deprecated This method is not part of the public API and will be removed in version 5.0.
+     *             Internal Kafka code should use {@link org.apache.kafka.common.utils.internals.BytesUtils#increment(Bytes)} instead.
      */
+    @Deprecated
```
Comment (squah-confluent) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: We could add `since` and `forRemoval`. The same applies elsewhere.
```suggestion
    @Deprecated(since = "4.3", forRemoval = true)
```

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java [hunk 2]
```diff
@@ -146,7 +163,10 @@ private static String toString(final byte[] b, int off, int len) {
...
     public static Bytes increment(Bytes input) throws IndexOutOfBoundsException {
```
Comment (squah-confluent) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java:172]: I wonder if it's appropriate to replace the implementation of this method with a call to the internal `BytesUtils` method.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java
Comment (squah-confluent) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: I wonder if it's appropriate to replace the implementation of this class with an `extends ByteUtils.LexicographicByteArrayComparator`.

**Review by squah-confluent — COMMENTED** [review]
Thanks for the patch!

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 2 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java:172]: Thanks Sean, Good point. 
I will update the deprecated methods to delegate to BytesUtils instead of duplicating the implementation.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java [hunk 3]
```diff
@@ -146,57 +161,32 @@ private static String toString(final byte[] b, int off, int len) {
...
     }
 
     /**
      * A byte array comparator based on lexicograpic ordering.
+     * @deprecated This field is not part of the public API and will be removed in version 5.0.
+     *             Internal Kafka code should use {@link org.apache.kafka.common.utils.internals.BytesUtils#BYTES_LEXICO_COMPARATOR} instead.
      */
-    public static final ByteArrayComparator BYTES_LEXICO_COMPARATOR = new LexicographicByteArrayComparator();
+    @Deprecated(since = "4.3", forRemoval = true)
+    public static final BytesUtils.ByteArrayComparator BYTES_LEXICO_COMPARATOR = new LexicographicByteArrayComparator();
```
Comment (squah-confluent) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: We can't change the type of this field unfortunately.
```suggestion
    public static final ByteArrayComparator BYTES_LEXICO_COMPARATOR = new LexicographicByteArrayComparator();
```

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java [hunk 4]
```diff
@@ -146,57 +161,32 @@ private static String toString(final byte[] b, int off, int len) {
...
-        int compare(final byte[] buffer1, int offset1, int length1,
-                    final byte[] buffer2, int offset2, int length2);
+    /**
+     * A byte array comparator interface.
+     *
+     * @deprecated This interface is not part of the public API and will be removed in version 5.0.
+     *             Internal Kafka code should use {@link org.apache.kafka.common.utils.internals.BytesUtils.ByteArrayComparator} instead.
+     */
+    @Deprecated(since = "4.3", forRemoval = true)
+    public interface ByteArrayComparator extends BytesUtils.ByteArrayComparator {
```
Comment (squah-confluent) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: We can't extend the non public API interface, otherwise it implicitly needs to be part of the public API.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java [hunk 5]
```diff
@@ -146,57 +161,32 @@ private static String toString(final byte[] b, int off, int len) {
...
-                    offset1 == offset2 &&
-                    length1 == length2) {
-                return 0;
-            }
-
-            int end1 = offset1 + length1;
-            int end2 = offset2 + length2;
-            return Arrays.compareUnsigned(buffer1, offset1, end1, buffer2, offset2, end2);
-        }
+    private static class LexicographicByteArrayComparator extends BytesUtils.LexicographicByteArrayComparator {
```
Comment (squah-confluent) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: Does this work? The idea is that the public API interface is implemented by the private class we inherit from.
```suggestion
    private static class LexicographicByteArrayComparator extends BytesUtils.LexicographicByteArrayComparator implements ByteArrayComparator {
```

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 3 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: yeah, that would be a breaking change, thanks again :)

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 5 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: Thanks again Sean

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 4 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: True, rolled back

File: build.gradle [hunk 6]
```diff
@@ -2046,6 +2046,7 @@ project(':clients') {
     include "**/org/apache/kafka/common/security/scram/*"
     include "**/org/apache/kafka/common/security/token/delegation/*"
     include "**/org/apache/kafka/common/serialization/*"
+    include "**/org/apache/kafka/common/utils/Bytes.java"
```
Comment (chia7712) [inline build.gradle:2046]: Exposing a single file as public seems a bit odd to me. Maybe we could follow the pattern from #21412, where we moved the other classes to an internal package. WDYT?

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java [hunk 7]
```diff
@@ -146,57 +163,36 @@ private static String toString(final byte[] b, int off, int len) {
...
-                    length1 == length2) {
-                return 0;
-            }
-
-            int end1 = offset1 + length1;
-            int end2 = offset2 + length2;
-            return Arrays.compareUnsigned(buffer1, offset1, end1, buffer2, offset2, end2);
-        }
+    private static class LexicographicByteArrayComparator extends BytesUtils.LexicographicByteArrayComparator implements ByteArrayComparator {
+        // Empty - inherits implementation from BytesUtils, but explicitly declares it implements the local interface
```
Comment (squah-confluent) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: Thanks for updating the PR!

We can remove this comment. It's not really necessary.
```suggestion
```

File: clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+        }
+        if (carry == 0) {
+            return Bytes.wrap(ret);
+        } else {
+            throw new IndexOutOfBoundsException();
+        }
+    }
+
+    /**
+     * A byte array comparator based on lexicograpic ordering.
```
Comment (brandboat) [inline clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java]: ditto, `lexicographic`

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java [hunk 9]
```diff
@@ -146,57 +163,36 @@ private static String toString(final byte[] b, int off, int len) {
...
-        if (carry == 0) {
-            return wrap(ret);
-        } else {
-            throw new IndexOutOfBoundsException();
-        }
+        return BytesUtils.increment(input);
     }
 
     /**
      * A byte array comparator based on lexicograpic ordering.
```
Comment (brandboat) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: not directly related to this PR, would you mind do a minor typo fix here? 
```suggestion
     * A byte array comparator based on lexicographic ordering.
```

File: clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java [hunk 10]
```diff
@@ -0,0 +1,94 @@
...
+ * This class is for internal Kafka use only and is not part of the public API.
+ */
+public final class BytesUtils {
+
+    private BytesUtils() {
+        // Utility class, prevent instantiation
+    }
+
+    /**
+     * Increment the underlying byte array by adding 1. Throws an IndexOutOfBoundsException if incrementing would cause
```
Comment (brandboat) [inline clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java]: Could you please use javadoc `@throws`? This could make it a bit clear imo.

```
@throws IndexOutOfBoundsException if...
```

**Review by brandboat — COMMENTED** [review]
Thanks for the patch! Just some minor doc tweaks

File: build.gradle (hunk 6 above)
Comment (siddharthaDevineni) [reply build.gradle:2046]: You are right, it seems a bit odd. 
I will move the remaining classes, except Bytes, Time and Timer into the internals package and add the utils package to the javadoc. This would be much cleaner. Thanks for the input.
By the way, is it "internal" or "internals"? Because there is an "internals" package under "org.apache.kafka.streams.state", "org.apache.kafka.common.config", "org.apache.kafka.common.header", "org.apache.kafka.common.metrics", and many more.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 7 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: sure, thanks Sean.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 9 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: Thanks for the correction

File: clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java (hunk 10 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java]: Yeah, you are right. That makes more sense, thanks.

File: build.gradle (hunk 6 above)
Comment (siddharthaDevineni) [reply build.gradle:2046]: I looked into following the pattern from #21412 and moving non-public classes to an internals subpackage. However, this introduces a complication: many of the utils classes are referenced in auto-generated code produced by the MessageGenerator.

When I attempted the reorganization, I got compilation errors like these are just a few of many:

Addressing this would require updating the MessageGenerator templates, regenerating all message files, and extensive testing - significantly beyond what was discussed in KIP-1247.

Given this complexity, what's the best path forward? Should this broader reorganization be handled separately, or is there a simpler approach I am missing?

 ./gradlew clean :clients:compileJava :clients:compileTestJava :streams:compileJava :streams:compileTestJava
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
Starting build with version 4.3.0-SNAPSHOT (commit id f4d3bc03) using Gradle 9.2.1, Java 21 and Scala 2.13.18
Build properties: ignoreFailures=false, maxParallelForks=10, maxScalacThreads=8, maxTestRetries=0

> Task :streams:processMessages
MessageGenerator: processed 1 Kafka message JSON file(s).

> Task :clients:processMessages
MessageGenerator: processed 198 Kafka message JSON file(s).

> Task :clients:compileJava
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:41: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:42: error: cannot find symbol
import org.apache.kafka.common.utils.ImplicitLinkedHashCollection;
                                    ^
  symbol:   class ImplicitLinkedHashCollection
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:43: error: cannot find symbol
import org.apache.kafka.common.utils.ImplicitLinkedHashMultiCollection;
                                    ^
  symbol:   class ImplicitLinkedHashMultiCollection
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:548: error: package ImplicitLinkedHashMultiCollection does not exist
    public static class ApiVersion implements Message, ImplicitLinkedHashMultiCollection.Element {
                                                                                        ^
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/LeaderChangeMessage.java:39: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/SnapshotHeaderRecord.java:35: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/SnapshotFooterRecord.java:35: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/KRaftVersionRecord.java:35: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/VotersRecord.java:41: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/VotersRecord.java:42: error: cannot find symbol
import org.apache.kafka.common.utils.ImplicitLinkedHashCollection;
                                    ^
  symbol:   class ImplicitLinkedHashCollection
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/VotersRecord.java:43: error: cannot find symbol
import org.apache.kafka.common.utils.ImplicitLinkedHashMultiCollection;
                                    ^
  symbol:   class ImplicitLinkedHashMultiCollection
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/VotersRecord.java:711: error: cannot find symbol
    public static class EndpointCollection extends ImplicitLinkedHashMultiCollection<Endpoint> {
                                                   ^
  symbol:   class ImplicitLinkedHashMultiCollection
  location: class VotersRecord
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/VotersRecord.java:453: error: package ImplicitLinkedHashMultiCollection does not exist
    public static class Endpoint implements Message, ImplicitLinkedHashMultiCollection.Element {
                                                                                      ^
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:780: error: cannot find symbol
    public static class ApiVersionCollection extends ImplicitLinkedHashMultiCollection<ApiVersion> {
                                                     ^
  symbol:   class ImplicitLinkedHashMultiCollection
  location: class ApiVersionsResponseData
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:1053: error: cannot find symbol
    public static class SupportedFeatureKeyCollection extends ImplicitLinkedHashMultiCollection<SupportedFeatureKey> {
                                                              ^
  symbol:   class ImplicitLinkedHashMultiCollection
  location: class ApiVersionsResponseData
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:814: error: package ImplicitLinkedHashMultiCollection does not exist
    public static class SupportedFeatureKey implements Message, ImplicitLinkedHashMultiCollection.Element {
                                                                                                 ^
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:1326: error: cannot find symbol
    public static class FinalizedFeatureKeyCollection extends ImplicitLinkedHashMultiCollection<FinalizedFeatureKey> {
                                                              ^
  symbol:   class ImplicitLinkedHashMultiCollection
  location: class ApiVersionsResponseData
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ApiVersionsResponseData.java:1087: error: package ImplicitLinkedHashMultiCollection does not exist
    public static class FinalizedFeatureKey implements Message, ImplicitLinkedHashMultiCollection.Element {
                                                                                                 ^
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/ResponseHeaderData.java:36: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/RequestHeaderData.java:37: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/FetchRequestData.java:41: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/FetchResponseData.java:45: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;
                                    ^
  symbol:   class ByteUtils
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/FetchResponseData.java:46: error: cannot find symbol
import org.apache.kafka.common.utils.ImplicitLinkedHashCollection;
                                    ^
  symbol:   class ImplicitLinkedHashCollection
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/FetchResponseData.java:47: error: cannot find symbol
import org.apache.kafka.common.utils.ImplicitLinkedHashMultiCollection;
                                    ^
  symbol:   class ImplicitLinkedHashMultiCollection
  location: package org.apache.kafka.common.utils
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/FetchResponseData.java:2573: error: cannot find symbol
    public static class NodeEndpointCollection extends ImplicitLinkedHashMultiCollection<NodeEndpoint> {
                                                       ^
  symbol:   class ImplicitLinkedHashMultiCollection
  location: class FetchResponseData
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/FetchResponseData.java:2271: error: package ImplicitLinkedHashMultiCollection does not exist
    public static class NodeEndpoint implements Message, ImplicitLinkedHashMultiCollection.Element {
                                                                                          ^
/home/sidna/kafka/clients/build/generated/main/java/org/apache/kafka/common/message/MetadataResponseData.java:42: error: cannot find symbol
import org.apache.kafka.common.utils.ByteUtils;

Comment (chia7712) [reply build.gradle:2046]: You could modify the constants defined by `MessageGenerator` to fix the build error.

https://github.com/apache/kafka/blob/trunk/generator/src/main/java/org/apache/kafka/message/MessageGenerator.java#L87
https://github.com/apache/kafka/blob/trunk/generator/src/main/java/org/apache/kafka/message/MessageGenerator.java#L90
https://github.com/apache/kafka/blob/trunk/generator/src/main/java/org/apache/kafka/message/MessageGenerator.java#L124

Comment (siddharthaDevineni) [reply build.gradle:2046]: Fixed, thanks Chia.

But how should we proceed further?

Like Bytes, Time is exposed and since Time creates/uses Timer both these should be part of the public APIs (in the next KIP as disussed in KIP-1247), but we can't make them public without a KIP yet and we can't move them to the internals package either without avoiding breaking changes since they were already exposed (leaked) into public APIs.

If we include the entire package in the javadoc (`include "**/org/apache/kafka/common/utils/*"`), it would make Time and Timer officially public API without the discussion and design work that was explicitly deferred during KIP-1247 review.

What's different from #21412 here:

The record package reorganization worked because:
- `TimestampType` was the only exposed class -> stayed where it was and became public
- All other classes were truly internal -> moved safely

For utils:
- Multiple classes (Bytes, Time, Timer) are exposed -> can't move without corresponding KIPs

So, considering these constraints, for now till the next KIP is accepted to make Time and Timer public, it makes sense to include just the `Bytes.java` in the javadoc:
```gradle
include "**/org/apache/kafka/common/utils/Bytes.java"
```

WDYT? Am I missing a simpler approach here?

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 2 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java:172]: fixed, please resolve the thread if you are okay with it, thanks.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: fixed, please resolve the thread if you are okay with it, thanks.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 3 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: fixed, please resolve the thread if you are okay with it, thanks.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 4 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: fixed, please resolve the thread if you are okay with it, thanks.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 5 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: fixed, please resolve the thread if you are okay with it, thanks.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 7 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: fixed, please resolve the thread if you are okay with it, thanks.

File: clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java (hunk 8 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java]: fixed, please resolve the thread if you are okay with it, thanks.

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 9 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java]: fixed, please resolve the thread if you are okay with it, thanks.

File: clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java (hunk 10 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java]: fixed, please resolve the thread if you are okay with it, thanks.

File: build.gradle (hunk 6 above)
Comment (chia7712) [reply build.gradle:2046]: Make sense. Let's stick with `include "**/org/apache/kafka/common/utils/Bytes.java` and leave `Time`, `Timer`, and `Bytes` in their original package. That could minimize the surprise. Also, it would be helpful to add comments to `package-info.java` mentioning the KIP that will discuss the exposition of the `Time` and `Timer` classes. WDYT?

Comment (siddharthaDevineni) [reply build.gradle:2046]: Done, please check

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java [hunk 11]
```diff
@@ -34,6 +43,14 @@ public class Bytes implements Comparable<Bytes> {
...
+    /**
+     * Creates a Bytes instance wrapping the given byte array.
+     *
+     * <p>The provided array becomes the backing storage for the object.
+     *
+     * @param bytes the byte array to wrap, or null
+     * @return a new Bytes instance, or null if the input is null
+     */
     public static Bytes wrap(byte[] bytes) {
         if (bytes == null)
```
Comment (chia7712) [inline clients/src/main/java/org/apache/kafka/common/utils/Bytes.java:56]: Does `Bytes` constructor accept a `null` input? If not, we should document this behaviour and add a strict null check. If it does, we need to handle `null` in all methods. For instance, `toString` would currently throw an NPE

Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java:56]: Thank you Chia, you are right on the inconsistency of null handling.

Actually, `toString()` does handle null - the private `toString(byte[], int, int)` method has a null check:
```java
private static String toString(final byte[] b, int off, int len) {
    if (b == null)
        return result.toString();  // Returns empty string
```

But the method `compareTo()` will throw an NPE if the internal `bytes` array is null, since the comparator accesses `bytes.length` without any null check.

I have added a null check to the constructor using `Objects.requireNonNull()` so that:
- `wrap(null)` continues to return null (backward compatible)
- `new Bytes(null)` throws an NPE immediately (fail fast)
- All Bytes instances are guaranteed to have a non-null bytes array
- No null checks needed in methods like `compareTo()`

This makes it now consistent i guess?

Comment (chia7712) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java:56]:
```java
    @Override
    public String toString() {
        return Bytes.toString(bytes, 0, bytes.length);
    }
```
`bytes.length` could cause NPE

File: clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java [hunk 12]
```diff
@@ -0,0 +1,94 @@
...
+            throw new IndexOutOfBoundsException();
+        }
+    }
+
+    /**
+     * A byte array comparator based on lexicographic ordering.
+     */
+    public static final ByteArrayComparator BYTES_LEXICO_COMPARATOR = new LexicographicByteArrayComparator();
+
+    public interface ByteArrayComparator extends Comparator<byte[]>, Serializable {
```
Comment (chia7712) [inline clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java]: Is implementing `Serializable` still necessary here? I don't think this class is intended for java's native serialization

**Review by chia7712 — COMMENTED** [review]
@siddharthaDevineni thanks for this patch. overall LGTM, except for one small comment

File: clients/src/main/java/org/apache/kafka/common/utils/Bytes.java (hunk 11 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/Bytes.java:56]: Yeah, right, my apologies as i overlooked the `bytes.length` in the caller method.

File: clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java (hunk 12 above)
Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java]: You are right again, we don't need it. The backward compatibility is maintained through the deprecated public `Bytes.ByteArrayComparator` interface, but same is not the case for internals interface.

Thank you Chia.

Comment (siddharthaDevineni) [reply clients/src/main/java/org/apache/kafka/common/utils/internals/BytesUtils.java]: @chia7712 - I removed Serializable from the internals `ByteArrayComparator` interface as you suggested. 

SpotBugs was complaining about SE_COMPARATOR_SHOULD_BE_SERIALIZABLE for the LexicographicByteArrayComparator class, so I added an exclusion in gradle/spotbugs-exclude.xml since this is internal code not intended for serialization.

The deprecated public interface still keeps Serializable for backward compatibility.

**Comment by siddharthaDevineni** [comment]
Hi @chia7712 @mjsax,

With code freeze coming up on March 18, wanted to check on the status of this PR. I believe I have addressed all feedback so far. Is there anything else needed for approval?

Ready to make any quick adjustments if needed.

Thank you

**Review by chia7712 — APPROVED** [review]

File: build.gradle (hunk 6 above)
Comment (chia7712) [reply build.gradle:2046]: I'm going to merge this PR. The cleanup of other classes in `org/apache/kafka/common/utils` will be handled in the follow-up PRs

Comment (chia7712) [reply build.gradle:2046]: opened https://issues.apache.org/jira/browse/KAFKA-20297
