### PR TITLE
HOTFIX: fix incompatible types: Optional<TimestampAndOffset> cannot be converted to Option<TimestampAndOffset>

### PR DESCRIPTION
**Pull request by FrankYang0529**
The error was introduced by https://github.com/apache/kafka/commit/220c57852100e895b460e56d1132a3c9239aaa59.

Run `./gradlew build -x test` or `./gradlew checkstyleMain checkstyleTest spotlessCheck` on trunk and will get following error:

```
> Configure project :
Starting build with version 4.1.0-SNAPSHOT (commit id e8863c9e) using Gradle 8.10.2, Java 21 and Scala 2.13.15
Build properties: ignoreFailures=false, maxParallelForks=12, maxScalacThreads=8, maxTestRetries=0

> Task :share-coordinator:processMessages
MessageGenerator: processed 4 Kafka message JSON files(s).

> Task :raft:processMessages
MessageGenerator: processed 1 Kafka message JSON files(s).

> Task :storage:processMessages
MessageGenerator: processed 5 Kafka message JSON files(s).

> Task :transaction-coordinator:processMessages
MessageGenerator: processed 2 Kafka message JSON files(s).

> Task :metadata:processMessages
MessageGenerator: processed 25 Kafka message JSON files(s).

> Task :group-coordinator:processMessages
MessageGenerator: processed 48 Kafka message JSON files(s).

> Task :clients:processMessages
MessageGenerator: processed 190 Kafka message JSON files(s).

> Task :clients:processTestMessages
MessageGenerator: processed 4 Kafka message JSON files(s).

> Task :clients:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :core:compileScala
[Error] /Users/poanyang/Project/apache/kafka/core/src/main/java/kafka/server/share/ShareFetchUtils.java:171:  error: incompatible types: Optional<TimestampAndOffset> cannot be converted to Option<TimestampAndOffset>
javac exited with exit code 1

> Task :core:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileScala'.
> javac returned non-zero exit code

* Try:
> Run with --info option to get more log output.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 19s
328 actionable tasks: 39 executed, 289 up-to-date
```

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by m1a2st** [comment]
Hello @mumrah, It seen our CI are missing some check, Should we open a Jira to add a step for `./gradlew checkstyleMain checkstyleTest spotlessCheck`.

**Review by clolov — APPROVED** [review]
Thanks for the quick turnaround! The moment the build passes I will merge it

**Comment by mumrah** [comment]
@m1a2st / @clolov / @FrankYang0529 It looks like #18100 was not up to date with trunk before it was merged. 

On trunk, 220c578521 builds just fine. On 18100, the last commit 435c3365ff71 (after merging trunk) also builds fine, however this commit was from a week ago. Even though there was a breaking change on trunk, it was not noticed by Git because it conflicted in a more subtle way than just the diff.

Since we build the contents of the PR, and not the contents of trunk + PR, errors like this can occur. To avoid it, just be sure to get a green build with a recent trunk before merging. This is a problem we are hoping to solve with the merge queue once it becomes available.

**Comment by mumrah** [comment]
@m1a2st we can see here that the trunk CI job is failing as expected

https://github.com/apache/kafka/actions/runs/12430932187

**Comment by m1a2st** [comment]
Thank @mumrah for your explanation!

**Comment by clolov** [comment]
The latest build succeeded, so proceeding to merge
