### PR TITLE
KAFKA-12744: dependency upgrade: `argparse4j` 0.7.0 -->> 0.9.0

### PR DESCRIPTION
**Pull request by dejan2609**
Corresponding JIRA ticket: https://issues.apache.org/jira/browse/KAFKA-12744

Related unmerged PR: #10626 

Release notes:
- https://github.com/argparse4j/argparse4j/releases/tag/argparse4j-0.8.0
- https://github.com/argparse4j/argparse4j/releases/tag/argparse4j-0.8.1
- https://github.com/argparse4j/argparse4j/releases/tag/argparse4j-0.9.0

Only one class import has been changed:
- https://github.com/argparse4j/argparse4j/blob/argparse4j-0.7.0/src/main/java/net/sourceforge/argparse4j/internal/HelpScreenException.java 
- https://github.com/argparse4j/argparse4j/blob/argparse4j-0.9.0/main/src/main/java/net/sourceforge/argparse4j/helper/HelpScreenException.java

Note: I opted to leave deprecated `argparse4j` **_ArgumentParsers.newArgumentParser_** [method](https://github.com/argparse4j/argparse4j/pull/73/files#diff-323147dbff2561c34143f89493b7a8fd5f69652d47e929518936097d7ae6ac4f) in Kafka code **_as-is_** and postpone [argparse4j code migration](https://argparse4j.github.io/migration.html#to-0-8-0)  for some future PR (or maybe even to use some other library for parsing: https://github.com/timtiemens/javacommandlineparser?tab=readme-ov-file#java-command-line-parsing-libraries).

@mimaison feel free to review.

### CODE REVIEW

**Comment by dejan2609** [comment]
Update: **_LICENSE-binary_** file is changed also (hence rebase/force-push).

**Review by mimaison — COMMENTED** [review]
Thanks for the PR. There's a checkstyle violation:
```
Execution failed for task ':shell:spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/org/apache/kafka/shell/command/Commands.java
          @@ -21,12 +21,12 @@
           import·org.apache.kafka.shell.state.MetadataShellState;

           import·net.sourceforge.argparse4j.ArgumentParsers;
          +import·net.sourceforge.argparse4j.helper.HelpScreenException;
           import·net.sourceforge.argparse4j.inf.ArgumentParser;
           import·net.sourceforge.argparse4j.inf.ArgumentParserException;
           import·net.sourceforge.argparse4j.inf.Namespace;
           import·net.sourceforge.argparse4j.inf.Subparser;
           import·net.sourceforge.argparse4j.inf.Subparsers;
          -import·net.sourceforge.argparse4j.helper.HelpScreenException;

           import·org.jline.reader.Candidate;

  Run './gradlew :shell:spotlessApply' to fix these violations.
```

**Comment by dejan2609** [comment]
Pardon me for not testing with checkstyle in a first place @mimaison.

Anyway, I fixed imports but Gradle build fails again:
`warning: [deprecation] newArgumentParser(String) in ArgumentParsers has been deprecated`

I will paste complete stack trace here (and will use next comment to present alternatives).
```
dejan@dejan:~/kafka$ ./gradlew checkstyleMain checkstyleTest spotlessCheck
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
Starting build with version 4.1.0-SNAPSHOT (commit id f17682ab) using Gradle 8.10.2, Java 17 and Scala 2.13.15
Build properties: ignoreFailures=false, maxParallelForks=8, maxScalacThreads=8, maxTestRetries=0

> Task :generator:compileJava
/home/dejan/kafka/generator/src/main/java/org/apache/kafka/message/MessageGenerator.java:371: warning: [deprecation] newArgumentParser(String) in ArgumentParsers has been deprecated
            .newArgumentParser("message-generator")
            ^
error: warnings found and -Werror specified
/home/dejan/kafka/generator/src/main/java/org/apache/kafka/message/checker/MetadataSchemaCheckerTool.java:43: warning: [deprecation] newArgumentParser(String) in ArgumentParsers has been deprecated
        ArgumentParser argumentParser = ArgumentParsers.
                                                       ^
1 error
2 warnings

> Task :generator:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generator:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.

BUILD FAILED in 1m
54 actionable tasks: 9 executed, 45 up-to-date
dejan@dejan:~/kafka$
```

**Comment by dejan2609** [comment]
So, herewith alternatives: 
1. relax Checkstyle rules via exception (i.e. don't fail the build for `ArgumentParsers.newArgumentParser` method deprecation warning mentioned above) **_OR_**
2. use my old PR [#10626](https://github.com/apache/kafka/pull/10626) and replace method (`ArgumentParsers.newArgumentParser` with  `ArgumentParsers.newFor`) as mentioned [here](https://argparse4j.github.io/migration.html#to-0-8-0)

@mimaison LMK which option sounds better for you.

**Comment by mimaison** [comment]
Both options are valid, but ideally we'd want to refactor the current logic to not use the deprecated APIs.

At a glance this does not seem too complicated. As mentioned in https://github.com/apache/kafka/pull/10626 you'll also have to ensure this does not change the behavior of the impacted tools.

**Comment by dejan2609** [comment]
Ok then, code refactoring it is.

**Comment by dejan2609** [comment]
Can't allocate time for this so I will just close this PR.
Corresponding  JIRA ticket https://issues.apache.org/jira/browse/KAFKA-12744 is marked with `help-wanted` and `up-for-grabs` labels.
