### PR TITLE
KAFKA-20168: Upgrade Jetty from 12.0.22 to 12.0.32 to fix CVE-2025-5115

### PR DESCRIPTION
**Pull request by mingyen066**
Upgrade Jetty from 12.0.22 to 12.0.32 to address
https://github.com/jetty/jetty.project/security/advisories/GHSA-mmxm-8w33-wc4h
(MadeYouReset HTTP/2 DoS, CVSS 7.7 HIGH).

  Note that CVE-2025-5115 only affects the
`org.eclipse.jetty.http2:jetty-http2-common` module. Kafka does not
depend on this module — its embedded Jetty servers (Connect RestServer
and Trogdor JsonRestServer) only use HTTP/1.1 via `ServerConnector`
without any                     `HTTP2ServerConnectionFactory`
configuration. As such, the attack vector is not applicable. This
upgrade from 12.0.22 to 12.0.32 is to keep the dependency up to date.

4.0: https://github.com/apache/kafka/pull/21462
4.1: https://github.com/apache/kafka/pull/21461

Reviewers: Chia-Ping Tsai <chia7712@gmail.com>

### CODE REVIEW

**Comment by chia7712** [comment]
@mingyen066 could you open PRs for 4.1 and 4.0? we can handle 4.2 and 3.9 later since they are currently in the release process.

**Comment by mingyen066** [comment]
@chia7712 Sure

**Review by chia7712 — APPROVED** [review]

**Comment by omkreddy** [comment]
I’ve noticed that Jetty 12 actually [depends on](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server/12.0.32/dependencies) slf4j-api 2.x. Ideally, we should have upgraded slf4j-api along with Jetty 12. 

We likely haven’t observed issues so far because there were no breaking usages up to Jetty 12.0.29?. However, during testing with Jetty 12.0.32 and slf4j-api 1.7.36, we have observed the following error when debug logs were enabled:

```
java.lang.NoSuchMethodError: 'org.slf4j.spi.LoggingEventBuilder org.slf4j.Logger.atDebug()'
        at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.completeChannelCallback(HttpChannelState.java:1588)
        at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.succeeded(HttpChannelState.java:1531)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.onCompleted(ServletChannel.java:763)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:428)
        at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:470)
        at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
```

So upgrading Jetty without also upgrading slf4j-api can lead to runtime failures?

cc @chia7712 @viktorsomogyi @AndrewJSchofield

**Comment by viktorsomogyi** [comment]
@omkreddy this is a very good point you raise. I've tried to reproduce this with Connect standalone, however I can't really see it. Debug logging seems to work fine with Jetty. Did you have a more nuanced example? Would you mind sharing it?
Looking at the CVE though it seems like Jetty 12.0.22 already has this fix too. If proves necessary, on the 4.1 and 4.0 branches I think we can still revert these changes as it seems like the least invasive change to avoid any more regressions.
While a revert provides a quick relief on trunk, the underlying problem there may be bigger as slf4j1 could possibly prevent us from applying security fixes in some libraries.

**Comment by omkreddy** [comment]
Just to clarify, I was testing with the **kafka-rest** artifacts, not directly with Kafka. I mainly wanted to highlight the Jetty/SLF4J API issue.

I can see the above NoSuchMethodError logs in some Connect integration tests with debug enabled (e.g ExampleConnectIntegrationTest):
* Requests are processed and responses are sent successfully — the tests are not failing because of this.
* However, the `NoSuchMethodError` in `completeChannelCallback` prevents Jetty from properly transitioning the connection state machine to its final state.
* This can lead to connection-related issues such as:

  * Connections getting stuck in the `COMPLETED` state and not being cleaned up
  * Jetty’s idle timeout firing repeatedly on zombie connections
  * Server shutdown failures due to stuck connections

**Comment by chia7712** [comment]
> Looking at the CVE though it seems like Jetty 12.0.22 already has this fix too. 

The security fix mentioned by is actually available starting from 12.0.25
see https://github.com/jetty/jetty.project/security/advisories/GHSA-mmxm-8w33-wc4h

It seems we might have overlooked the SLF4J dependency constrains when discussing KIP-1032. The fluent API usage that @omkreddy pointed out was introduced in https://github.com/jetty/jetty.project/commit/1d1d1a90c81a1df0b539aa8593bdb7907200bd07 and was pushed to Jetty 12.0.30+

I've cross-checked the source code of Jetty 12.0.25, and it appears the Fluent API was only used in their test code at that point, which wouldn't trigger the `NoSuchMethodError` at runtime for us

https://github.com/jetty/jetty.project/commit/c112a1c5380153f708fcf47b8d25588801eb842f

Since upgrading to SLF4J is not an option for Kafka at this moment, the most straightforward solution is to downgrade Jetty to 12.0.25. This keeps us on Jetty 12 as per KIP-1032 and ensure we have the necessary CVE fixes without SLF4J 1.x incompatibility

@omkreddy @viktorsomogyi WDYT?

**Comment by omkreddy** [comment]
@chia7712 Yes, we can downgrade Jetty to 12.0.25 for the upcoming bug-fix releases.
we should also look for a solution for future releases, as we can expect future CVEs in Jetty.

**Comment by mingyen066** [comment]
Thanks @omkreddy @chia7712 for spotting the issue.
I filed multiple PRs to downgrade Jetty to 12.0.25.
I’ll revisit this later and see if we can find a better solution.

**Comment by AndrewJSchofield** [comment]
@mingyen066 Thanks. I was just preparing RC0 for 4.1.2, but I will abandon it and work on RC1 instead with this fix.

**Comment by chia7712** [comment]
> we should also look for a solution for future releases, as we can expect future CVEs in Jetty.

opened https://issues.apache.org/jira/browse/KAFKA-20216 to trace it

**Comment by mimaison** [comment]
> we should also look for a solution for future releases, as we can expect future CVEs in Jetty.

Here they are:
- [CVE-2025-11143](https://www.cve.org/CVERecord?id=CVE-2025-11143): https://issues.apache.org/jira/browse/KAFKA-20283
- [CVE-2026-1605](https://www.cve.org/CVERecord?id=CVE-2026-1605): https://issues.apache.org/jira/browse/KAFKA-20270

**Comment by mingyen066** [comment]
@mimaison Thanks for the heads-up. I plan to issue a KIP this week to discuss a shadow solution.

**Comment by chia7712** [comment]
opened https://issues.apache.org/jira/browse/KAFKA-20344 to update jetty to latest version of 12.0.x - the usage of slf4j 2 APIs are gone. see https://github.com/jetty/jetty.project/commit/25001a13c2b4529cc1c9d2d2405fcde98d1ccb04
