### PR TITLE
HOTFIX: fix compilation error

### PR DESCRIPTION
**Pull request by mjsax**
Two PRs got merged in parallel. They don't agree to each other:

-
https://github.com/apache/kafka/commit/1dc4cef0bcade1cfc347af4684dece9c998fa8d4
-
https://github.com/apache/kafka/commit/d2cbb26e2b4dec3fc96c5fb666f74af5104793ca

This PR fixes the introduced compilation error.

Reviewers: Manikumar Reddy <manikumar.reddy@gmail.com>, Lucas Brutschy
 <lbrutschy@confluent.io>, Chia-Ping Tsai <chia7712@gmail.com>, Nick
 Telford <nick.telford@gmail.com>, TengYao Chi <frankvicky@apache.org>

### CODE REVIEW

**Review by omkreddy — APPROVED** [review]

**Review by lucasbru — APPROVED** [review]

**Review by chia7712 — APPROVED** [review]
LGTM

**Review by nicktelford — APPROVED** [review]

**Review by frankvicky — APPROVED** [review]
