### PR TITLE
HOTFIX: Compilation error in CommandLineUtils

### PR DESCRIPTION
**Pull request by hachikuji**
This was broken by #6084. The syntax works with Scala 2.12, but not 2.11.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Comment by cmccabe** [comment]
LGTM

**Comment by hachikuji** [comment]
Built locally. I will go ahead and merge.
