### PR TITLE
MINOR: Remove lock contention while adding sensors

### PR DESCRIPTION
**Pull request by divijvaidya**
When we want to add a sensor to `Metrics.java`, we synchronize the entire method. However both, `sensors` and `childrenSensors` are concurrent hash maps and full method synchronization is not required. 

This PR removes the method level synchronization and uses the properties of concurrent hash map to ensure thread safety. 

The motivation of this change is code hygiene improvement and there is no known bottleneck by this lock contention.

Behaviour after the change:
- sensors with different names can be added to the `sensors` map concurrently (vs. earlier where only one could be added at a time)

### CODE REVIEW

**Comment by divijvaidya** [comment]
The build is failing with:
```
[2022-12-01T20:35:07.343Z] FAILURE: Build completed with 2 failures.

[2022-12-01T20:35:07.343Z] 

[2022-12-01T20:35:07.343Z] 1: Task failed with an exception.

[2022-12-01T20:35:07.343Z] -----------

[2022-12-01T20:35:07.343Z] * What went wrong:

[2022-12-01T20:35:07.343Z] Execution failed for task ':connect:file:compileJava'.

[2022-12-01T20:35:07.343Z] > Compilation failed; see the compiler error output for details.

[2022-12-01T20:35:07.343Z] 

[2022-12-01T20:35:07.343Z] * Try:

[2022-12-01T20:35:07.343Z] > Run with --stacktrace option to get the stack trace.

[2022-12-01T20:35:07.343Z] > Run with --info or --debug option to get more log output.

[2022-12-01T20:35:07.343Z] > Run with --scan to get full insights.

[2022-12-01T20:35:07.343Z] ==============================================================================

[2022-12-01T20:35:07.343Z] 

[2022-12-01T20:35:07.343Z] 2: Task failed with an exception.

[2022-12-01T20:35:07.343Z] -----------

[2022-12-01T20:35:07.343Z] * What went wrong:

[2022-12-01T20:35:07.343Z] Unable to make progress running work. There are items queued for execution but none of them can be started

[2022-12-01T20:35:07.343Z] 

[2022-12-01T20:35:07.343Z] * Try:

[2022-12-01T20:35:07.343Z] > Run with --stacktrace option to get the stack trace.

[2022-12-01T20:35:07.343Z] > Run with --info or --debug option to get more log output.

[2022-12-01T20:35:07.343Z] > Run with --scan to get full insights.

[2022-12-01T20:35:07.343Z] ==============================================================================
```

But strangely it passes locally for me:
```
diviv@147dda742970:~/oss/kafka|minor-lock-contention ⇒  ./gradlew :connect:file:compileJava

> Configure project :
Starting build with version 3.4.0-SNAPSHOT (commit id 15aa84a7) using Gradle 7.6, Java 17 and Scala 2.13.8
Build properties: maxParallelForks=12, maxScalacThreads=8, maxTestRetries=0

BUILD SUCCESSFUL in 15s
6 actionable tasks: 5 executed, 1 up-to-date
```

**Comment by divijvaidya** [comment]
Rebased from trunk. Test failures are unrelated.
```
Build / JDK 11 and Scala 2.13 / testFailureToFenceEpoch(String).quorum=kraft – kafka.api.TransactionsTest

Build / JDK 11 and Scala 2.13 / [1] true – org.apache.kafka.streams.integration.SmokeTestDriverIntegrationTest

Build / JDK 17 and Scala 2.13 / testSecondaryRefreshAfterElapsedDelay() – org.apache.kafka.common.security.oauthbearer.internals.secured.RefreshingHttpsJwksTest

Build / JDK 17 and Scala 2.13 / [3] Type=Raft-CoReside, Name=testDescribeQuorumReplicationSuccessful, MetadataVersion=3.3-IV3, Security=PLAINTEXT – kafka.admin.MetadataQuorumCommandTest

Build / JDK 17 and Scala 2.13 / testNoConsumeWithoutDescribeAclViaSubscribe() – kafka.api.SaslGssapiSslEndToEndAuthorizationTest

Build / JDK 17 and Scala 2.13 / testTaskRequestWithOldStartMsGetsUpdated() – org.apache.kafka.trogdor.coordinator.CoordinatorTest

Build / JDK 8 and Scala 2.12 / testWakeupAfterSyncGroupReceivedExternalCompletion() – org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest

Build / JDK 8 and Scala 2.12 / shouldWriteLatestOffsetsToCheckpointOnShutdown[exactly_once] – org.apache.kafka.streams.integration.EosIntegrationTest
```

**Comment by divijvaidya** [comment]
@mimaison please take a look when you get a chance! Thanks.

**Review by showuon — APPROVED** [review]
LGTM!

**Comment by showuon** [comment]
Re-run the jenkins: https://ci-builds.apache.org/job/Kafka/job/kafka-pr/job/PR-12940/4/

**Review by SoulPancake — APPROVED** [review]

**Comment by ijuma** [comment]
The previous approach provided stronger atomicity than the new approach. Have you made sure the weaker semantics don't cause issues?

Given that `sensors` and `childrenSensors` can now be out of sync with each other, the code may be harder to reason about and diagnose. It's not an improvement from a code hygiene perspective, there would have to be a scalability/performance motivation to go down this path.

**Comment by divijvaidya** [comment]
Thank you for your review @ijuma. I see that you back to reviewing PRs after a bit of break :) 

I did not understand your comment about weaker semantics. I believe that the semantics are actually stronger in the new code as explained below. Please let me know if I am mistaken.

I have also provided an example of latency benefit that this code change brings in scenario of multiple connection setup.

**Earlier code**
1. Return the sensor if exists
2. Create a sensor if not exists
3. Add this sensor to `sensors` map
4. Acquire a lock (computeIfAbsent does it) over the `parent` key in `childrenSensors` and append the new sensor to it.

case 1: exception occurs  while adding to `childrenSensors`
Note that if an exception occurs at step 4, the sensor still exists in the `sensors` map. Hence, the earlier code is **not atomic!** and there might be an inconsistency between `sensors` and `childrenSensors` where `sensors` may have more entries than `childrenSensors`.

case 2: exception occurs  while adding to `sensors` 
Note that if an exception occurs at step 3, no modifications will be done by the code.

**New code**
1. Acquire a lock over the sensor name in `sensor` map
2. Return the sensor if exists 
3. Create a sensor if not exists
4. Acquire a lock (computeIfAbsent does it) over the `parent` key in `childrenSensors` and append the new sensor to it.
5. Add this sensor to `sensors` map

case 1: exception occurs  while adding to `childrenSensors`
Note that if an exception occurs at step 4, the new sensor **will not be added** to the `sensors` map. **This semantic is stronger than earlier code** since, it ensures there won't be a scenario where where `sensors` may have more entries than `childrenSensors`.

case 2: exception occurs while adding to `sensors`
An exception could occur when creating sensor (at `new Sensor`) in which case no value will be entered into `childrenSensors` and if `new Sensor` is successful, there can never be a NPE or a Class cast exception. Hence, there is no scenario where a sensor will be added to `childrenSensors` and not to `sensors`.

**Advantages of new code**
1. Allows concurrent access (even for `get` scenarios) into `sensors` map. `sensors` map is accessed in the connection initialisation code path in `Selector.java` by multiple network threads. Improving lock contention for this path will improve connection setup time for scenarios when a burst of new connection setup is received (e.g. in case of client restart).
2. New code has stronger atomic semantics as demonstrated in case 1 of new code above.

**Comment by divijvaidya** [comment]
I am moving this PR to draft mode. Please hold the review.

I need to add a proof here that the when we relax synchronisation amongst operations in this class by allowing concurrent access (e.g. add/removeSensors can operate concurrently), we are not violating any semantics. I will also make some changes to `metrics` entity in this class. Currently, we acquire a coarse grained lock on the entire class and I will explore whether we can divide it into finer locks (or allow concurrent access) with `metrics` entity, `sensors` entity and `childrenSensors` entity.
