### PR TITLE
KAFKA-17739: Clean up build.gradle to adopt the minimum Java version as 11

### PR DESCRIPTION
**Pull request by frankvicky**
JIRA: [KAFKA-17739](https://issues.apache.org/jira/browse/KAFKA-17739)
> We are planning to drop JDK 8. This is part of the upgrade from JDK 8 to JDK 11. You can see the full plan here: [KAFKA-12894](https://issues.apache.org/jira/browse/KAFKA-12894)
> 1. minJavaVersion=11
> 2. remove sourceCompatibility and targetCompatibility
> 3. cleanup all compatibility checks

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

File: clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/OAuthBearerSaslClientProvider.java [hunk 1]
```diff
@@ -27,7 +27,7 @@ public class OAuthBearerSaslClientProvider extends Provider {
 
     @SuppressWarnings("this-escape")
     protected OAuthBearerSaslClientProvider() {
-        super("SASL/OAUTHBEARER Client Provider", 1.0, "SASL/OAUTHBEARER Client Provider for Kafka");
+        super("SASL/OAUTHBEARER Client Provider", "1.0", "SASL/OAUTHBEARER Client Provider for Kafka");
         put("SaslClientFactory." + OAuthBearerLoginModule.OAUTHBEARER_MECHANISM,
```
Comment (frankvicky) [inline clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/OAuthBearerSaslClientProvider.java:31]: `new Provider(String, double, String)` has been deprecated since Java 9.
The documentation recommends using `new Provider(String, String, String)` instead.

File: storage/src/test/java/org/apache/kafka/server/log/remote/storage/LocalTieredStorage.java [hunk 2]
```diff
@@ -254,9 +255,10 @@ public void configure(Map<String, ?> configs) {
 
         if (transfererClass != null) {
             try {
-                transferer = (Transferer) getClass().getClassLoader().loadClass(transfererClass).newInstance();
-
-            } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | ClassCastException e) {
+                transferer = (Transferer) getClass().getClassLoader().loadClass(transfererClass)
+                        .getDeclaredConstructor().newInstance();
```
Comment (frankvicky) [inline storage/src/test/java/org/apache/kafka/server/log/remote/storage/LocalTieredStorage.java:259]: `clazz.newInstance()` has been deprecated since Java 9. 
The documentation recommends using `clazz.getDeclaredConstructor().newInstance()` instead.

File: trogdor/src/test/java/org/apache/kafka/trogdor/common/JsonSerializationTest.java [hunk 3]
```diff
@@ -74,7 +74,7 @@ private <T> void verify(T val1) throws Exception {
         Class<T> clazz = (Class<T>) val1.getClass();
         T val2 = JsonUtil.JSON_SERDE.readValue(bytes, clazz);
         for (Field field : clazz.getDeclaredFields()) {
-            boolean wasAccessible = field.isAccessible();
+            boolean wasAccessible = field.canAccess(val2);
```
Comment (frankvicky) [inline trogdor/src/test/java/org/apache/kafka/trogdor/common/JsonSerializationTest.java:81]: `.isAccessible()` has been deprecated since Java 9.
The documentation recommends using `.canAccess(object)` instead.

File: build.gradle [hunk 4]
```diff
@@ -309,25 +304,10 @@ subprojects {
...
+    options.release = minJavaVersion
     addParametersForTests(name, options)
   }
 
-  java {
-    // We should only set this if Java version is < 9 (--release is recommended for >= 9), but the Scala plugin for IntelliJ sets
-    // `-target` incorrectly if this is unset
-    sourceCompatibility = minJavaVersion
-    targetCompatibility = minJavaVersion
-  }
```
Comment (cadonna) [inline build.gradle:329]: Is this correct? Does the Scala plugin no more suffer from the issue described in the comment? 
KIP-750 to modify these not to delete them.

File: gradle/spotbugs-exclude.xml [hunk 5]
```diff
@@ -547,5 +547,10 @@ For a detailed description of spotbugs bug categories, see https://spotbugs.read
         </Or>
         <Bug pattern="RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT"/>
     </Match>
+    <Match>
+        <!-- Suppress warning about using static DateFormat in a multithreaded context -->
+        <Class name="org.apache.kafka.tools.ReplicaVerificationTool$ReplicaBuffer"/>
+        <Bug pattern="STCAL_INVOKE_ON_STATIC_DATE_FORMAT_INSTANCE"/>
+    </Match>
```
Comment (cadonna) [inline gradle/spotbugs-exclude.xml:554]: Is this safe? There is a reason for that warning. Why should we suppress it?

**Review by cadonna — COMMENTED** [review]
Thanks for the PR @frankvicky !

I had a few comments. Bear with me if my questions are silly. I am not familiar with this part of the code.

File: gradle/spotbugs-exclude.xml (hunk 5 above)
Comment (frankvicky) [reply gradle/spotbugs-exclude.xml:554]: No, it might be a concern, but I suppress it since this test is going to be deleted. 
I don't think it's very meaningful to fix it at this moment. 🤔 

https://github.com/apache/kafka/blob/bb6ebd83f9a0f9b2a37704f1f37b78a48cf480e1/tools/src/main/java/org/apache/kafka/tools/ReplicaVerificationTool.java#L115

File: build.gradle (hunk 4 above)
Comment (frankvicky) [reply build.gradle:329]: Thanks for pointing out.
I think it is a mistake, I will add it back

File: build.gradle [hunk 6]
```diff
@@ -328,6 +315,10 @@ subprojects {
     targetCompatibility = minJavaVersion
   }
 
+  compileJava {
```
Comment (chia7712) [inline build.gradle]: why we need this when line#307 does similar change?

**Review by chia7712 — COMMENTED** [review]
@frankvicky thanks for this patch.

File: build.gradle (hunk 6 above)
Comment (frankvicky) [reply build.gradle]: Oops, I got it wrong. I will fix it soon.

File: build.gradle (hunk 4 above)
Comment (chia7712) [reply build.gradle:329]: I've checked the latest Scala plugin, and the `-target` option is no longer included.
```
        <parameter value="-release" />
        <parameter value="11" />
```
Additionally, based on the discussion (https://youtrack.jetbrains.com/issue/SCL-21039/Dont-set-parameter-value-target-in-.idea-scalacompiler.xml-when-Gradle-build-is-using-release-flag-applies-for-Gradle-8.0.1#focus=Comments-27-7380486.0-0), it seems the issue has already been fixed.

Comment (frankvicky) [reply build.gradle:329]: Thanks for information 😺

Comment (chia7712) [reply build.gradle:329]: @frankvicky Could you please also update KIP-750?

Comment (frankvicky) [reply build.gradle:329]: done

**Review by chia7712 — APPROVED** [review]

File: build.gradle (hunk 4 above)
Comment (omkreddy) [reply build.gradle:329]: @chia7712 @frankvicky looks like this removal of sourceCompatibility, targetCompatibility Java compile options from build.gradle is not setting the Scala compile target version correctly. I have prepared a build with JDK17 and getting UnsupportedClassVersionError for Scala classes while trying to start with JDK 11.

Comment (omkreddy) [reply build.gradle:329]: I tried to fix here: https://github.com/apache/kafka/pull/17546

**Comment by mjsax** [comment]
@frankvicky @chia7712 

I just recognized that I cannot build `trunk` using Java 11 any longer:

I tracked it down to this PR -- before this commit, it works, but this commit seems to break it:
```
$ ./gradlew systemTestLibs

> Configure project :
Starting build with version 4.0.0-SNAPSHOT (commit id 1ece9184) using Gradle 8.10, Java 11 and Scala 2.13.15
Build properties: ignoreFailures=false, maxParallelForks=16, maxScalacThreads=8, maxTestRetries=0

[...]

> Task :jmh-benchmarks:compileJava
warning: No processor claimed any of these annotations: java.base/java.lang.SuppressWarnings,java.base/java.lang.Override
error: warnings found and -Werror specified
1 error
1 warning

> Task :jmh-benchmarks:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jmh-benchmarks:compileJava'.
> Compilation failed; see the compiler error output for details.

[...]
```

`trunk` still compiles with Java17 and Java21 though. Can you take a look?

**Comment by chia7712** [comment]
@mjsax thanks for this report. we will check it today

**Comment by chia7712** [comment]
@mjsax I can't reproduce the error. Could you please clean (`./gradlew clean`) project and try it again?

```
jenkins@50cc5fcf9828:~/repo$ ./gradlew clean systemTestLibs

> Configure project :
Starting build with version 4.0.0-SNAPSHOT (commit id d36b24f4) using Gradle 8.10.2, Java 11 and Scala 2.13.15
Build properties: ignoreFailures=false, maxParallelForks=24, maxScalacThreads=8, maxTestRetries=0

> Task :raft:processMessages
MessageGenerator: processed 1 Kafka message JSON files(s).

> Task :transaction-coordinator:processMessages
MessageGenerator: processed 2 Kafka message JSON files(s).

> Task :storage:processMessages
MessageGenerator: processed 5 Kafka message JSON files(s).

> Task :share-coordinator:processMessages
MessageGenerator: processed 4 Kafka message JSON files(s).

> Task :streams:processMessages
MessageGenerator: processed 1 Kafka message JSON files(s).

> Task :metadata:processMessages
MessageGenerator: processed 25 Kafka message JSON files(s).

> Task :group-coordinator:processMessages
MessageGenerator: processed 32 Kafka message JSON files(s).

> Task :clients:processMessages
MessageGenerator: processed 186 Kafka message JSON files(s).

> Task :clients:processTestMessages
MessageGenerator: processed 4 Kafka message JSON files(s).

> Task :clients:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 36s

```

**Comment by mjsax** [comment]
Still getting the error with "clean" option. What Java are you using?
```
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by mjsax** [comment]
There is only one `@SuppressWarnings("deprecation")` in the jmh module in `ProducerResponseBenchmark.java` -- if I remove it, one of both errors goes away.

But there is 40 `@Overwrite` annotation. Not sure if there is a single offending one, or if all a are a problem. 40 is too many to try the out one-by-one.

Not sure if this is useful information to track it down?

**Comment by chia7712** [comment]
@mjsax it seems that is a JDK issue (https://bugs.openjdk.org/browse/JDK-8193214), and the fix is backported to `11.0.13`. I check the build on 11.0.13 and it works.
```
BUILD SUCCESSFUL in 15m 18s
561 actionable tasks: 561 executed
root@1f5e165f48b1:/kafka# cd kafka/^C
root@1f5e165f48b1:/kafka# java -version
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
root@1f5e165f48b1:/kafka# 

```

**Comment by mjsax** [comment]
Thanks!
