### PR TITLE
KAFKA-9952; Remove immediate fetch completion logic on high watermark updates

### PR DESCRIPTION
**Pull request by hachikuji**
For KIP-392, we added logic to make sure that high watermark changes are propagated to followers without delay in order to improve end to end latency when fetching from followers. The downside of this change is that it increases the rate of fetch requests from followers which can have a noticeable impact on performance (see KAFKA-9731). 

To fix that problem, we have already modified the code so that we only propagate high watermark changes immediately when a replica selector is used (which is not the default). However, leaving this logic around means that it is risky to enable follower fetching since it changes the follower request rate, which can have a big impact on overall broker performance. 

This patch disables immediate propagation of the high watermark more generally. Instead, users can use the max wait time in order to control the worst-case latency. Note that this is typically only a problem anyway for low-throughput clusters since otherwise we will always have a steady rate of high watermark updates.

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

File: core/src/main/scala/kafka/server/DelayedFetch.scala [hunk 1]
```diff
@@ -120,14 +119,6 @@ class DelayedFetch(delayMs: Long,
...
               }
             }
-
-            if (fetchMetadata.isFromFollower) {
-              // Case H check if the follower has the latest HW from the leader
-              if (partition.getReplica(fetchMetadata.replicaId)
-                .exists(r => offsetSnapshot.highWatermark.messageOffset > r.lastSentHighWatermark)) {
-                return forceComplete()
-              }
-            }
```
Comment (ijuma) [inline core/src/main/scala/kafka/server/DelayedFetch.scala:130]: Interesting. This could cause an early return for the leader case too, right?

**Review by ijuma — COMMENTED** [review]
Thanks for the PR. I agree with this change. As discussed offline, if we could send the updated hw when the fetch is satisfied without going to purgatory, it would avoid a situation where an additional fetch is currently required. More concretely, the hw would not be `0` in the following test:

https://github.com/apache/kafka/commit/fbfda2c4ad889c731aa52b5214e0521f187f8db6#diff-dd66c2b818ed445a159cd1334f4139b2R1001

**Comment by hachikuji** [comment]
@ijuma Yeah, I'm working on it. If it's ok with you, can we do that in a separate patch? I think there are a few related problems we can fix:

1. What you mentioned. We should propagate the updated high watermark to the follower.
2. Currently the high watermark we return from Log.read could be lower than the offset of the data returned in the fetch response.
3. Fetch responses return the log start offset, the high watermark, and the last stable offset. Currently I don't think we have invariants on the relative order between these offsets, but it would be nice to enforce `logStartOffset <= lastStableOffset <= highWatermark`.

I started working on these problems, but found that it's quite a bit of work, so probably better done in a new PR. Note, however, that I did push a minor cleanup of `LogReadResult`

**Comment by ijuma** [comment]
Makes sense, let me review this one as it stands then.

**Comment by ijuma** [comment]
retest this please

File: core/src/main/scala/kafka/server/DelayedFetch.scala (hunk 1 above)
Comment (hachikuji) [reply core/src/main/scala/kafka/server/DelayedFetch.scala:130]: Yeah, we missed this in the other patch.

File: core/src/main/scala/kafka/server/ReplicaManager.scala [hunk 2]
```diff
@@ -109,9 +109,19 @@ case class LogReadResult(info: FetchDataInfo,
...
+      s"info=$info, " +
+      s"highWatermark=$highWatermark, " +
+      s"leaderLogStartOffset=$leaderLogStartOffset, " +
+      s"leaderLogEndOffset=$leaderLogEndOffset, " +
+      s"followerLogStartOffset=$followerLogStartOffset, " +
+      s"fetchTimeMs=$fetchTimeMs, " +
+      s"preferredReadReplica=$preferredReadReplica, " +
+      s"lastStableOffset=$lastStableOffset, " +
+      s"error=$error" +
+      ")"
```
Comment (ijuma) [inline core/src/main/scala/kafka/server/ReplicaManager.scala:123]: Could we use the `toString` from the case class?

File: core/src/main/scala/kafka/server/ReplicaManager.scala [hunk 3]
```diff
@@ -1100,10 +1100,8 @@ class ReplicaManager(val config: KafkaConfig,
             leaderLogEndOffset = readInfo.logEndOffset,
             followerLogStartOffset = followerLogStartOffset,
             fetchTimeMs = fetchTimeMs,
-            readSize = adjustedMaxBytes,
```
Comment (ijuma) [inline core/src/main/scala/kafka/server/ReplicaManager.scala:1103]: Do we still need to compute `adjustedMaxBytes`? Also, do you know why we don't need `readSize` anymore? What change made it unnecessary?

**Review by ijuma — COMMENTED** [review]
Looks good overall, a couple of questions below.

**Comment by hachikuji** [comment]
retest this please

File: core/src/main/scala/kafka/server/ReplicaManager.scala (hunk 3 above)
Comment (hachikuji) [reply core/src/main/scala/kafka/server/ReplicaManager.scala:1103]: We can get the read size already from the `Records` object. The code must have been changed at some point to use this. It looks like `adjustedMaxBytes` is still sent through in the call to `Partition.readRecords`.

File: core/src/main/scala/kafka/server/ReplicaManager.scala (hunk 2 above)
Comment (hachikuji) [reply core/src/main/scala/kafka/server/ReplicaManager.scala:123]: Do we get the labels from the default `toString`? In the past, I thought it would only show the values.

File: core/src/main/scala/kafka/server/ReplicaManager.scala (hunk 3 above)
Comment (ijuma) [reply core/src/main/scala/kafka/server/ReplicaManager.scala:1103]: Thanks, makes sense.

File: core/src/main/scala/kafka/server/ReplicaManager.scala (hunk 2 above)
Comment (ijuma) [reply core/src/main/scala/kafka/server/ReplicaManager.scala:123]: That's true. You have to write `toString` yourself if you want labels. We could write a utility method like so (didn't try too compile it and skipped some details like commas):

```scala
def productToString(product: Product): String = {
  val builder = new StringBuilder
  sb.append(product.prefix)
  for (i <- 0 until product.productArity) {
    builder.append(product.productElementName(i))
      .append("=")
      .append(product.productElement(i))
  }
  sb.build()
}
```

Then we can call that method from any case class `toString` where we want this format. Avoids some duplication and forgetting to update `toString` when new fields are added.

Comment (hachikuji) [reply core/src/main/scala/kafka/server/ReplicaManager.scala:123]: Ok, I added something like that.

Comment (ijuma) [reply core/src/main/scala/kafka/server/ReplicaManager.scala:123]: Sweet!

**Review by ijuma — APPROVED** [review]
Thanks for the PR, LGTM.

**Comment by ijuma** [comment]
Argh:

> 09:53:20 [Error] /home/jenkins/jenkins-slave/workspace/kafka-pr-jdk8-scala2.12/core/src/main/scala/kafka/utils/CoreUtils.scala:326: value productElementName is not a member of Product

**Comment by ijuma** [comment]
Looks like `productToString` only works with Scala 2.13. :(

**Comment by hachikuji** [comment]
Bummer. Guess I will revert the commit.

**Review by andrewchoi5 — APPROVED** [review]
