### PR TITLE
KAFKA-14386: Return TopicAssignment from the ReplicaPlacer

### PR DESCRIPTION
**Pull request by andrewgrantcflt**
### JIRA
https://issues.apache.org/jira/browse/KAFKA-14386

### Summary
This changes the `ReplicaPlacer` interface to return a class instead of a list of list of integers. There are two reasons for the suggestion. First, as mentioned in the JIRA, it will make the interface, arguably, a bit more readable and understandable by explicitly modeling the idea of topic and partition. Second and more importantly, it makes the interface more extendable in the future. Right now it would be challenging to add more metadata to the response. By having classes, we can easily add fields to them without breaking/changing the interface. For example, in the CreatePartitions RPC we are adding partitions to an existing topic and we might want to add some metadata to response making it clear which partition the assignment starts at which could look something like:

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

File: metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java [hunk 1]
```diff
@@ -1564,16 +1567,17 @@ void createPartitions(CreatePartitionsTopic topic,
...
         } else {
-            placements = clusterControl.replicaPlacer().place(new PlacementSpec(
+            partitionAssignments = clusterControl.replicaPlacer().place(new PlacementSpec(
                 startPartitionId,
                 additional,
                 replicationFactor
-            ), clusterDescriber);
-            isrs = placements;
+            ), clusterDescriber).assignments();
+            isrs = partitionAssignments.stream().map(x -> x.replicas()).collect(Collectors.toList());
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java]: How about:
```java
            isrs = partitionAssignments.stream().map(PartitionAssignment::replicas).collect(Collectors.toList());
```

File: metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java [hunk 2]
```diff
@@ -1564,16 +1567,17 @@ void createPartitions(CreatePartitionsTopic topic,
...
             }
         } else {
-            placements = clusterControl.replicaPlacer().place(new PlacementSpec(
+            partitionAssignments = clusterControl.replicaPlacer().place(new PlacementSpec(
                 startPartitionId,
                 additional,
                 replicationFactor
-            ), clusterDescriber);
-            isrs = placements;
+            ), clusterDescriber).assignments();
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java]: I think we can improve the formatting with something like:
```java
partitionAssignments = clusterControl.replicaPlacer().place(
    new PlacementSpec(...),
    clusterDescriber
).assignments()
```

File: metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.apache.kafka.metadata.placement;
+
+import java.util.List;
+
+/**
+ * The KRaft partition assignment.
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java]: I would remove the reference to KRaft.
> The partition placement.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/StripedReplicaPlacer.java [hunk 4]
```diff
@@ -440,6 +441,6 @@ public List<List<Integer>> place(
         for (int partition = 0; partition < placement.numPartitions(); partition++) {
             placements.add(rackList.place(placement.numReplicas()));
         }
-        return placements;
+        return new TopicAssignment(placements.stream().map(x -> new PartitionAssignment(x)).collect(Collectors.toList()));
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/metadata/placement/StripedReplicaPlacer.java]: How about:
```java
        return new TopicAssignment(
            placements.stream().map(PartitionAssignment::new).collect(Collectors.toList())
        );
```

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.apache.kafka.metadata.placement;
+
+import java.util.List;
+
+/**
+ * The KRaft topic assignment.
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java]: I would remove the reference to KRaft. The package name is `org.apache.kafka.metadata.placement` so it is unrelated to KRaft.

File: metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java [hunk 6]
```diff
@@ -407,13 +405,8 @@ public void testPlaceReplicas(int numUsableBrokers) throws Exception {
...
                     1,
                     (short) 3),
-                new ClusterDescriber() {
-                    @Override
-                    public Iterator<UsableBroker> usableBrokers() {
-                        return clusterControl.usableBrokers();
-                    }
-                }
-            );
+                    () -> clusterControl.usableBrokers()
```
Comment (jsancio) [inline metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java]: How about:
```java
                    clusterControl::usableBrokers
```

File: metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java [hunk 7]
```diff
@@ -407,13 +405,8 @@ public void testPlaceReplicas(int numUsableBrokers) throws Exception {
...
+            ).assignments().stream().map(x -> x.replicas()).collect(Collectors.toList());
```
Comment (jsancio) [inline metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java]: Did you consider changing the type of `results` to `TopicAssignment` and fixing the `for` loop below?

File: metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java [hunk 8]
```diff
@@ -101,7 +102,7 @@ public Iterator<UsableBroker> usableBrokers() {
                 return brokers.iterator();
             }
         };
-        return placer.place(placementSpec, cluster);
+        return placer.place(placementSpec, cluster).assignments().stream().map(x -> x.replicas()).collect(Collectors.toList());
```
Comment (jsancio) [inline metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java]: Did you consider changing the signature of this method to return `TopicPlacement` and adjusting the test above to use that type?

File: metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+ *
+ * The assignment is represented as a list of integers where each integer is the replica ID.
+ */
+public class PartitionAssignment {
+    private List<Integer> replicas;
+
+    public PartitionAssignment(List<Integer> replicas) {
+        this.replicas = replicas;
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java]: We should make this type immutable.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java [hunk 10]
```diff
@@ -0,0 +1,39 @@
...
+ */
+public class TopicAssignment {
+    private List<PartitionAssignment> assignments;
+
+    public TopicAssignment(List<PartitionAssignment> assignments) {
+        this.assignments = assignments;
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java]: We should make this type immutable.

**Review by jsancio — COMMENTED** [review]
Thanks for the changes @andymg3 .

Should we also improve the `PartitionRegistration` type to use a `PartitionAssignment` instead of `int[] replicas`?

File: metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+package org.apache.kafka.metadata.placement;
+
+import java.util.List;
+
+/**
+ * The KRaft partition assignment.
+ *
+ * The assignment is represented as a list of integers where each integer is the replica ID.
+ */
+public class PartitionAssignment {
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java:31]: Let's add unittests for this type.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java [hunk 12]
```diff
@@ -0,0 +1,39 @@
...
+ */
+
+package org.apache.kafka.metadata.placement;
+
+import java.util.List;
+
+/**
+ * The KRaft topic assignment.
+ */
+public class TopicAssignment {
```
Comment (jsancio) [inline metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java:30]: Let's add unittests for this type.

File: metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java (hunk 1 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java]: Makes sense. Changed.

File: metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java (hunk 2 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java]: Changed.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java (hunk 3 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java]: Done.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java (hunk 9 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java]: Done.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/StripedReplicaPlacer.java (hunk 4 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/StripedReplicaPlacer.java]: Agree. Updated.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java (hunk 5 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java]: Done.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java (hunk 10 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java]: Agreed. Done.

File: metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java (hunk 6 above)
Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java]: Compiler doesnt like that: `Iterator<UsableBroker> is not a functional interface`

File: metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java (hunk 7 above)
Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java]: Just changed this code snippet to:
```
 List<PartitionAssignment> results = clusterControl.replicaPlacer().place(
                new PlacementSpec(0,
                    1,
                    (short) 3),
                    () -> clusterControl.usableBrokers()
            ).assignments();
            HashSet<Integer> seen = new HashSet<>();
  for (Integer result : results.get(0).replicas()) {

```

File: metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java (hunk 11 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java:31]: Added a couple. Since its a pretty simple class I only added two - let me know if there's anything you think I'm missing.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java (hunk 12 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java:30]: As with `PartitionAssignment` I have added a couple. Since its a pretty simple class I only added two - let me know if there's anything you think I'm missing.

File: metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java (hunk 8 above)
Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java]: I was originally trying to reduce the number of changes. But I think it makes sense to return a TopicAssignment so we dont have to keep creating another list.

**Comment by andrewgrantcflt** [comment]
> Thanks for the changes @andymg3 .
> 
> Should we also improve the `PartitionRegistration` type to use a `PartitionAssignment` instead of `int[] replicas`?

Thanks for the review @jsancio. As of now I dont see much benefit in changing that type. In `PartitionRegistration` we also have `[]int isr`, `int[] removingReplicas`, and `int[] addingReplicas`. I'm inclined to leave `replicas` as is for consistency - I think it reads a bit better when they're all the same type. They're often processed at the same time as well, so having to deal with both types may be a bit cumbersome. There are quite a few places in the codebase that use the `replicas` field and in practice if we were to use `PartitionAssignment`  all callers would mostly just call `PartitionAssignment.replicas()` anyways. So overall I don't see much benefit in introducing the type. 

What do you think?

File: metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java (hunk 6 above)
Comment (jsancio) [reply metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java]: Did you use `clusterControl::usableBrokers` or `clusterControl.usableBrokers()`?

File: metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java [hunk 13]
```diff
@@ -95,12 +94,7 @@ private List<List<Integer>> place(
         PlacementSpec placementSpec = new PlacementSpec(startPartition,
             numPartitions,
             replicationFactor);
-        ClusterDescriber cluster = new ClusterDescriber() {
-            @Override
-            public Iterator<UsableBroker> usableBrokers() {
-                return brokers.iterator();
-            }
-        };
+        ClusterDescriber cluster = () -> brokers.iterator();
```
Comment (jsancio) [inline metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java]: How about `brokers::iterator`?

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java (hunk 10 above)
Comment (jsancio) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java]: This type is not immutable. The user can `this.assignments().add(new PartitionAssignment(...))`.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java (hunk 9 above)
Comment (jsancio) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java]: This type is not immutable. The user can `this.replicas().add(100)`.

File: metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java [hunk 14]
```diff
@@ -0,0 +1,59 @@
...
+            ),
+            new PartitionAssignment(
+                    Arrays.asList(1, 2, 0)
+            )
+        );
+
+        for (int i = 0; i < partitionAssignments.size(); i++) {
+            for (int j = 0; j < partitionAssignments.size(); j++) {
+                if (i == j) {
+                    assertEquals(partitionAssignments.get(i), partitionAssignments.get(j));
```
Comment (jsancio) [inline metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java:50]: This assumes that the implementation of `equals` doesn't compare the references to determine equality.

This comment also applies to `TopicAssignmentTest`.

**Review by jsancio — COMMENTED** [review]
> There are quite a few places in the codebase that use the replicas field and in practice if we were to use PartitionAssignment all callers would mostly just call PartitionAssignment.replicas() anyways. So overall I don't see much benefit in introducing the type.

Sounds good.

File: metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java (hunk 6 above)
Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java]: `clusterControl::usableBrokers` doesnt compile. `clusterControl.usableBrokers()` is what I have and it does compile.

Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java]:
```
+++ b/metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java
@@ -405,7 +405,7 @@ public class ClusterControlManagerTest {
                 new PlacementSpec(0,
                     1,
                     (short) 3),
-                    () -> clusterControl.usableBrokers()
+                    () -> clusterControl::usableBrokers
             ).assignments();
             HashSet<Integer> seen = new HashSet<>();
             for (Integer result : results.get(0).replicas()) {
...@...kafka % ./gradlew jar

> Configure project :
Starting build with version 3.4.0-SNAPSHOT (commit id 4ac9307e) using Gradle 7.6, Java 1.8 and Scala 2.13.8
Build properties: maxParallelForks=12, maxScalacThreads=8, maxTestRetries=0

> Task :metadata:compileTestJava FAILED
... kafka/metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java:408: error: incompatible types: bad return type in lambda expression
                    () -> clusterControl::usableBrokers
                          ^
    java.util.Iterator is not a functional interface
      multiple non-overriding abstract methods found in interface java.util.Iterator
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
```

File: metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java (hunk 13 above)
Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java]: Same as above. That actually doesn't compile:
```
> Task :metadata:compileTestJava FAILED
... /kafka/metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java:97: error: incompatible types: bad return type in lambda expression
        ClusterDescriber cluster = () -> brokers::iterator;
                                         ^
    java.util.Iterator is not a functional interface
      multiple non-overriding abstract methods found in interface java.util.Iterator
1 error
```

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java (hunk 10 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java]: I can update this to:
```
    public TopicAssignment(final List<PartitionAssignment> assignments) {
        this.assignments = Collections.unmodifiableList(new ArrayList<>(assignments));
    }
```
Does that make sense?

File: metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java (hunk 14 above)
Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java:50]: Correct. I think thats what we want? Looking at the other classes where we override `equals` I think they're the same?

Comment (jsancio) [reply metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java:50]: Right but this test is uninteresting if the `equals` implementation is optimized to compare the references first. E.g.
```java
boolean equals(Object that) {
  if (this == that) return true;
  ...
}

File: metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java (hunk 13 above)
Comment (jsancio) [reply metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java]: You want `ClusterDescribe cluster = brokers::iterator;`

File: metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java (hunk 6 above)
Comment (jsancio) [reply metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java]: You want
```
+++ b/metadata/src/test/java/org/apache/kafka/controller/ClusterControlManagerTest.java
@@ -405,7 +405,7 @@ public class ClusterControlManagerTest {
                 new PlacementSpec(0,
                     1,
                     (short) 3),
-                    () -> clusterControl.usableBrokers()
+                    clusterControl::usableBrokers
             ).assignments();
             HashSet<Integer> seen = new HashSet<>();
             for (Integer result : results.get(0).replicas()) {
```

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java (hunk 10 above)
Comment (jsancio) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java]: Yes. Ideally you would also clone/copy the parameter pass in the constructor because the caller has a reference to `assignments` and can update it.

File: metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java (hunk 14 above)
Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java:50]: Thats true. If `equals` is updated to compare references we arent checking the rest of the code. I can add in another assert like:
```
assertEquals(partitionAssignments.get(i), new PartitionAssignment(partitionAssignments.get(i).replicas()));
```
Does that make sense to you?

File: metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java (hunk 13 above)
Comment (andrewgrantcflt) [reply metadata/src/test/java/org/apache/kafka/metadata/placement/StripedReplicaPlacerTest.java]: I simplified further to:
```
        PlacementSpec placementSpec = new PlacementSpec(startPartition,
            numPartitions,
            replicationFactor);
        return placer.place(placementSpec, brokers::iterator);
```

File: metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java (hunk 14 above)
Comment (jsancio) [reply metadata/src/test/java/org/apache/kafka/metadata/placement/PartitionAssignmentTest.java:50]: Yes.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java (hunk 10 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/TopicAssignment.java]: Updated to:
```
    public TopicAssignment(final List<PartitionAssignment> assignments) {
        this.assignments = Collections.unmodifiableList(new ArrayList<>(assignments));
    }
```
Also commented on both this class and `PartitionAssignment` that they're immutable.

File: metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java (hunk 9 above)
Comment (andrewgrantcflt) [reply metadata/src/main/java/org/apache/kafka/metadata/placement/PartitionAssignment.java]: Updated to:
```
    public PartitionAssignment(final List<Integer> replicas) {
        this.replicas = Collections.unmodifiableList(new ArrayList<>(replicas));
    }
```

**Review by jsancio — APPROVED** [review]
LGTM
