### PR TITLE
MINOR: Gradle version update: 9.2.1 -->> 9.3.1

### PR DESCRIPTION
**Pull request by dejan2609**
release notes:  - https://docs.gradle.org/9.3.0/release-notes.html  -
https://docs.gradle.org/9.3.1/release-notes.html

:information_source: Notes:
- done by-the-book (procedure mentioned here `gradle/wrapper/README.md`
was followed)
- it makes sense to merge this with Gradle Shadow plugin version
upgrade: #20866

Reviewers: Chia-Ping Tsai <chia7712@gmail.com>

### CODE REVIEW

**Comment by dejan2609** [comment]
FYI @chia7712

**Review by chia7712 — APPROVED** [review]

**Comment by chia7712** [comment]
```
* What went wrong:
Execution failed for task ':examples:spotlessJavaCheck'.
> There were 8 lint error(s), they must be fixed or suppressed.
  src/main/java/kafka/examples/Consumer.java:LINE_UNDEFINED removeUnusedImports(java.lang.NoClassDefFoundError) com/google/googlejavaformat/java/RemoveUnusedImports (...)
  src/main/java/kafka/examples/ExactlyOnceMessageProcessor.java:LINE_UNDEFINED removeUnusedImports(java.lang.NoClassDefFoundError) com/google/googlejavaformat/java/RemoveUnusedImports (...)
  src/main/java/kafka/examples/KafkaConsumerProducerDemo.java:LINE_UNDEFINED removeUnusedImports(java.lang.NoClassDefFoundError) com/google/googlejavaformat/java/RemoveUnusedImports (...)
  src/main/java/kafka/examples/KafkaExactlyOnceDemo.java:LINE_UNDEFINED removeUnusedImports(java.lang.NoClassDefFoundError) com/google/googlejavaformat/java/RemoveUnusedImports (...)
  src/main/java/kafka/examples/KafkaProperties.java:LINE_UNDEFINED removeUnusedImports(java.lang.NoClassDefFoundError) com/google/googlejavaformat/java/RemoveUnusedImports (...)
  src/main/java/kafka/examples/Producer.java:LINE_UNDEFINED removeUnusedImports(java.lang.NoClassDefFoundError) com/google/googlejavaformat/java/RemoveUnusedImports (...)
  src/main/java/kafka/examples/TransactionalClientDemo.java:LINE_UNDEFINED removeUnusedImports(java.lang.NoClassDefFoundError) com/google/googlejavaformat/java/RemoveUnusedImports (...)
  src/main/java/kafka/examples/Utils.java:LINE_UNDEFINED removeUnusedImports(java.lang.NoClassDefFoundError) com/google/googlejavaformat/java/RemoveUnusedImports (...)
  Resolve these lints or suppress with `suppressLintsFor`
```
These errors happen on my local machine sometimes. I'll dig into it.

**Comment by chia7712** [comment]
someone has reported it (https://github.com/diffplug/spotless/issues/2850). I will revert this commit for now

**Comment by chia7712** [comment]
I've opened https://issues.apache.org/jira/browse/KAFKA-20182 to trace this issue

**Comment by dejan2609** [comment]
@chia7712 Sorry for this, I should have checked. I subscribed to that spotless issue and will try to redeem myself.

**Comment by dejan2609** [comment]
Just an update: it seems that the issue mentioned above by @chia7712 is a corner case.
In my own setup spotless task execution is working just fine (see console output below).

Conclusion: I will try to dig around and to provide more information for the Spotless team.

```
dejan@box:~/kafka$ date
Sat 21 Feb 09:22:08 CET 2026
dejan@box:~/kafka$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.4 LTS
Release:	24.04
Codename:	noble
dejan@box:~/kafka$ uname -r
6.8.0-100-generic
dejan@box:~/kafka$ git log -2 --oneline 
9d16751ffc (HEAD -> Gradle-9.3.1, origin/Gradle-9.3.1) MINOR: Gradle version update: 9.2.1 -->> 9.3.1
2df7c75fd5 MINOR: Fix requests version conflict with ducktape in tests/setup.py (#21415)
dejan@box:~/kafka$ ./gradlew clean spotlessCheck

> Configure project :
Starting build with version 4.3.0-SNAPSHOT (commit id 9d16751f) using Gradle 9.3.1, Java 17 and Scala 2.13.18
Build properties: ignoreFailures=false, maxParallelForks=8, maxScalacThreads=8, maxTestRetries=0

[Incubating] Problems report is available at: file:///home/dejan/kafka/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 10.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/9.3.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 14s
196 actionable tasks: 196 executed
Consider enabling configuration cache to speed up this build: https://docs.gradle.org/9.3.1/userguide/configuration_cache_enabling.html
dejan@box:~/kafka$ date
Sat 21 Feb 09:22:51 CET 2026
dejan@box:~/kafka$
```

**Comment by dejan2609** [comment]
📢 **Another update:** POC for a spotless plugin issue testing (mentioned above) is created here: https://github.com/dejan2609/spotless-cache-repro-master/tree/main
