### PR TITLE
KAFKA-16131: Only update directoryIds if the metadata version supports DirectoryAssignment

### PR DESCRIPTION
**Pull request by pprovenzano**
We only want to send directory assignments if the metadata version supports it.

### CODE REVIEW

**Comment by pprovenzano** [comment]
Test failures are unrelated to the PR.

File: metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java [hunk 1]
```diff
@@ -46,6 +46,18 @@ public final class FeaturesImage {
         ZkMigrationState.NONE
     );
 
+    public static final FeaturesImage LATEST = new FeaturesImage(
```
Comment (cmccabe) [inline metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java]: Hmm... I'd rather not add `FeaturesImage.LATEST` here since it feels like something that is only for testing. Can we just add this to `ReplicaManagerTest.scala`, for now?

LGTM once that's addressed

**Comment by cmccabe** [comment]
Thanks for the quick response on this one, @pprovenzano . LGTM once you address the one comment I made.

File: metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java (hunk 1 above)
Comment (pprovenzano) [reply metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java]: Done!

**Comment by pprovenzano** [comment]
Test failures are not related.

**Comment by mjsax** [comment]
@pprovenzano @cmccabe -- it seems this PR did break `trunk` build.

```
> Task :core:compileTestScala
[Error] /Users/matthias/IdeaProjects/kafka/core/src/test/scala/unit/kafka/server/ReplicaManagerTest.scala:6178:23: value latest is not a member of object org.apache.kafka.server.common.MetadataVersion
one error found
```

Can you take a look and help to fix it?

**Comment by pprovenzano** [comment]
Looks like it is already fixed with:
MINOR: Fix compilation issue in ReplicaManagerTest (
<https://github.com/pprovenzano/kafka/commit/acab4657ddefe6dadf078203705ad85105c23db3>
apache#15222 <https://github.com/apache/kafka/pull/15222>)
<https://github.com/pprovenzano/kafka/commit/acab4657ddefe6dadf078203705ad85105c23db3>


The issue was caused by a collision of my change and the following:
KAFKA-16078: Be more consistent about getting the latest MetadataVersion
<https://github.com/pprovenzano/kafka/commit/7bf7fd99a50ba2dd71c41cd4c3623a3adce092b6>

--Proven

**Comment by mjsax** [comment]
Thanks. The fix was pushed after I left my comment. Glad it's resolved.

Yeah, I did expect that two overlapping PR got merged simultaneously.
