### PR TITLE
HOTFIX: Compilation error in GroupMetadataManagerTest

### PR DESCRIPTION
**Pull request by hachikuji**
Accidentally broke after merging KAFKA-7395. 

### Committer Checklist (excluded from commit message)
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation (including upgrade notes)

### CODE REVIEW

**Review by mjsax — APPROVED** [review]
LGTM.
